### ISSUE TITLE
Create javascript SDK for verification App

### ISSUE THREAD

**Issue by Sreejit-K** [Sunbird-RC/community#909] opened 2024-01-23 09:27 UTC
### What is the feature request for?

Others

### Verification sdk:
**Purpose of this sdk:**
The aim is to create a common utility package so that new users who are trying to create their own Verifier app can just import this as a npm package and have the vc validation code functionality right away.
	
Cururently, the library exports the following method:

**validateVC(vc, options)**
> **vc** - the verfiable credetntials
> **options** - valid issuers, ignore expiry date, etc. and more options as needed (maybe looking for a particular attributes in the vc, for example)

**Verification process:**
- get public key using did
- validate the vc - signature
- validate metadata - check for expiry time, issuer, etc. fields
- validate options if passed
- check if the vc is revoked

### Describe the feature clearly.

https://digit-discuss.atlassian.net/browse/DPG-2159

**Comment by manukalia29** [comment] 2024-01-23 09:34
@shiva-beehyv Please add description

**Comment by shiva-beehyv** [comment] 2024-01-23 11:37
### Verification sdk:
**Purpose of this sdk:**
The aim is to create a common utility package so that new users who are trying to create their own Verifier app can just import this as a npm package and have the vc validation code functionality right away.
	
Cururently, the library exports the following method:

**validateVC(vc, options)**
> **vc** - the verfiable credetntials
> **options** - valid issuers, ignore expiry date, etc. and more options as needed (maybe looking for a particular attributes in the vc, for example)

**Verification process:**
- get public key using did
- validate the vc - signature
- validate metadata - check for expiry time, issuer, etc. fields
- validate options if passed
- check if the vc is revoked

**Comment by srprasanna** [comment] 2024-01-24 03:37
Let's also look at downloading revocation list, which will be mentioned in the URL. @shiva-beehyv can you also list function signatures and libraries.

**Comment by srprasanna** [comment] 2024-02-07 04:46
Duplicate of https://github.com/Sunbird-RC/community/issues/917

**Closed as not planned by srprasanna** 2024-02-07 04:46 UTC
Labels: LTS v2.x, ref: Verification
